C++ = clang++
C++FLAGS = -std=c++2b -I ../smart_ptr/ 
SRC_PREFIX = /Users/admin/Documents/learning/implement_smartptr/cmake_implementation/../

main: objects
	$(C++) $(C++FLAGS) Main.o -o $(SRC_PREFIX)Main

objects: 
	$(C++) $(C++FLAGS) -c $(SRC_PREFIX)main.cpp -o Main.o
